spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5433}/${POSTGRES_DB_NAME:}?reWriteBatchedInserts=true
    username: ${POSTGRES_DB_USER:admin}
    password: ${POSTGRES_DB_PASSWORD:admin}
    driverClassName: org.postgresql.Driver
    hikari:
      minimumIdle: ${POSTGRES_DB_CONNECTION_IDLE:1}
      maximumPoolSize: ${POSTGRES_DB_CONNECTION_POOL:10}
      idleTimeout: 20000
      auto-commit: false
    name: PostgresDatasource
  jpa:
    generate-ddl: false
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      naming:
        physicalStrategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicitStrategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: validate  # create-drop / none

  liquibase:
    enabled: true
    changeLog: classpath:db/master.xml
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5433}/${POSTGRES_DB_NAME:}
    user: ${POSTGRES_DB_USER:admin}
    password: ${POSTGRES_DB_PASSWORD:admin}
