version: "3"
services:
  postgres:
    container_name: millerlab_postgres_container
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - pgsql-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pg"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: millerlab_pgadmin_container
    image: dpage/pgadmin4:7.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgsqladmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

  millerlab:
    container_name: millerlab
    image: fgrigoryan/millerlab:0.1
    environment:
      POSTGRES_DB_HOST: "postgres"
      POSTGRES_DB_PORT: "5432"
      POSTGRES_DB_NAME: "millerlab"
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - postgres

volumes:
  pgsql-data:
  pgsqladmin-data:

networks:
  postgres:
    driver: bridge